#!/usr/bin/env python
"""Make an html page in PWD comparing plots with reference side-by-side
"""

from __future__ import division, print_function
from glob import glob
import os
import sys

from viscid_test_common import plot_dir, ref_dir


header = """
<html>

<head>

<style>

* {
    font-family: Helvetica, "Trebuchet MS", Arial, sans-serif;
}

h1 {
    font-size: 3em;
    margin-top: 1em;
    margin-bottom: 1em;
    margin-left: auto;
    margin-right: auto;
}

table {
    border-collapse: collapse;
    float: center;
}

td {
    border-left: 1px solid #98bf21;
    border-right: 1px solid #98bf21;
}

td.leftmost {
    border-left: none;
}

td.rightmost {
    border-right: none;
}

th {
    font-size: 1.6em;
    text-align: center;
    padding-top: 0.4em;
    padding-bottom: 0.4em;
    background-color: #A7C942;
    color: #ffffff;
}

td.testname {
    color: #A7C942;
    // background-color: #ffffff;
    border-left: none;
    border-right: none;
    font-size: 1.6em;
    font-weight: bold;
    padding-top: 2.0em;
    padding-bottom: 0.0em;
}

td.plotname {
    text-align: center;
    color: #536421;
    // background-color: #ffffff;
    font-size: 1.0em;
    border-left: none;
    border-right: none;
    padding-top: 2.0em;
    padding-bottom: 1.5em;
}

.imgrow {
}

img {
    dispaly: block;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
    max-height: 100%;
}

.nofile {
}
</style>

</head>
<body>

<h1 align='center'>Viscid Test Plots</h1>
"""

footer = """
</body>
</html>
"""

def make_img_cell(fname, tdclass=""):
    if os.path.isfile(fname):
        meat = "<img src='{0}'/>".format(fname)
    else:
        meat = "<p class='nofile'>Plot '{0}' does not exist</p>".format(fname)
    return "<td align='center' class='{0}'>{1}</td>\n".format(tdclass, meat)

def make_plot(plot_name, rel_plot_dir=plot_dir, rel_ref_dir=ref_dir):
    meat = "<tr>\n"
    meat += "<td class='plotname' colspan='2'>{0}</td>\n".format(plot_name)
    meat += "</tr>\n"
    meat += "<tr class='imgrow'>\n"
    meat += make_img_cell(rel_plot_dir + "/" + plot_name, tdclass='leftmost') + "\n"
    meat += make_img_cell(rel_ref_dir + "/" + plot_name, tdclass='rightmost') + "\n"
    meat += "</tr>\n"
    return meat

def make_test_row(test_name):
    meat = "<tr><td class='testname' colspan='2'>Test: {0}</td></tr>".format(test_name)
    return meat

def main():
    output_dir = "./"

    rel_plot_dir = os.path.relpath(plot_dir)
    rel_ref_dir = os.path.relpath(ref_dir)

    # make up file list
    fmt = "png"
    test_plots = glob(plot_dir + "/*.{0}".format(fmt))
    ref_plots = glob(ref_dir + "/*.{0}".format(fmt))

    all_plots = [os.path.basename(s) for s in test_plots]
    all_plots += [os.path.basename(s) for s in ref_plots]
    all_plots = list(set(all_plots))
    all_plots.sort()

    html = header
    html += "<table>\n"
    html += "<tr><th>Test Plot</th><th>Reference Plot</th></tr>\n"

    last_test_name = ""
    for plot_name in all_plots:
        test_name = '-'.join(plot_name.split('-')[:-1])
        if test_name != last_test_name:
            html += make_test_row(test_name)
            last_test_name = test_name

        html += make_plot(plot_name, rel_plot_dir, rel_ref_dir)

    html += "</table>\n"
    html += footer

    with open(output_dir + "/summary.html", 'w') as f:
        f.write(html)
    return 0

if __name__ == "__main__":
    sys.exit(main())

##
## EOF
##
