#!/usr/bin/env python
"""Slice a glob of filenames.

The slice should be in square brackets and follow all the slicing
semantics used throughout viscid
"""

from __future__ import print_function
import argparse
import sys

from viscid.vutil import slice_globbed_filenames


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("glob_pattern", nargs=1, help="glob pattern")
    args = parser.parse_args()

    fnames = slice_globbed_filenames(args.glob_pattern[0])
    print(" ".join(fnames), file=sys.stdout)
    return 0

if __name__ == "__main__":
    sys.exit(main())

##
## EOF
##
