#!/usr/bin/env python

from __future__ import division, print_function
import sys

def main():
    if len(sys.argv) != 4 or '-h' in sys.argv or '--help' in sys.argv:
        print("usage: rgb2hex r g b")
        if len(sys.argv) != 4:
            return 1
        else:
            return 0

    r, g, b = [float(val) for val in sys.argv[1:]]

    if any([val < 0 for val in [r, g, b]]):
        raise ValueError("Values > 0 please")

    if any([val > 255 for val in [r, g, b]]):
        raise ValueError("Values between 0 and 255 please")

    if all([val <= 1.0 for val in [r, g, b]]):
        r, g, b = [val * 255 for val in [r, g, b]]

    r, g, b = [hex(int(val)).lstrip('0x').zfill(2) for val in [r, g, b]]
    as_str = "#{0}{1}{2}".format(r, g, b)
    print(as_str)

    return 0

if __name__ == "__main__":
    sys.exit(main())

##
## EOF
##
